const alumnos = [
  //3H
  { id_alumno: "1", nombre: "Bernal Mercedes", curso: "3-H", id_equipo: "3H1", github: "https://github.com/solbernall" },
  { id_alumno: "2", nombre: "González María Laura", curso: "3-H", id_equipo: "3H1", github: "https://github.com/solbernall" },
  { id_alumno: "3", nombre: "Borgstrand Martina", curso: "3-H", id_equipo: "3H2", github: "https://github.com/keylacarrion00" },
  { id_alumno: "4", nombre: "Carrion Keyla", curso: "3-H", id_equipo: "3H2", github: "https://github.com/keylacarrion01" },
  { id_alumno: "5", nombre: "Galluzzi Marcos", curso: "3-H", id_equipo: "3H3", github: "https://github.com/bian200171" },
  { id_alumno: "6", nombre: "Franzese Bianca", curso: "3-H", id_equipo: "3H3", github: "https://github.com/bian200172" },
  { id_alumno: "7", nombre: "Walter Ambar", curso: "3-H", id_equipo: "3H4", github: "https://github.com/ambar-mica" },
  { id_alumno: "8", nombre: "De Luca Micaela", curso: "3-H", id_equipo: "3H4", github: "https://github.com/ambar-mica" },
  { id_alumno: "9", nombre: "Blake Mateo", curso: "3-H", id_equipo: "3H5", github: "https://github.com/lukitasymateoficda" },
  { id_alumno: "10", nombre: "Rey Lucas", curso: "3-H", id_equipo: "3H5", github: "https://github.com/lukitasymateoficda" },
  { id_alumno: "11", nombre: "Castro  Daniel", curso: "3-H", id_equipo: "3H6", github: "https:///github.com/danielcastro2010" },
  { id_alumno: "12", nombre: "Costa  Lautaro", curso: "3-H", id_equipo: "3H6", github: "https:///github.com/danielcastro2010" },
  { id_alumno: "13", nombre: "López  Rocco", curso: "3-H", id_equipo: "3H7", github: "https:///github.com/roccoext09" },
  { id_alumno: "14", nombre: "Rossi Santiago", curso: "3-H", id_equipo: "3H7", github: "https:///github.com/roccoext09" },
  { id_alumno: "15", nombre: "Alaniz  Federico", curso: "3-H", id_equipo: "3H8", github: "https:///github.com/fedealanizz" },
  { id_alumno: "16", nombre: "Alvarez  Baldomero", curso: "3-H", id_equipo: "3H8", github: "https:///github.com/fedealanizz" },
  { id_alumno: "17", nombre: "Giroldi  Sofia", curso: "3-H", id_equipo: "3H9", github: "https:///github.com/sofigypalo" },
  { id_alumno: "18", nombre: "Sánchez  Paloma", curso: "3-H", id_equipo: "3H9", github: "https:///github.com/sofigypalo" },
  { id_alumno: "19", nombre: "de Pedro Sofía", curso: "3-H", id_equipo: "3H10", github: "https:///github.com/grupo4-lys" },
  { id_alumno: "20", nombre: "Suárez  Luciana ", curso: "3-H", id_equipo: "3H10", github: "https:///github.com/grupo4-lys" },
  { id_alumno: "21", nombre: "Canónico Renata", curso: "3-H", id_equipo: "3H11", github: "https:///github.com/renatacanonico" },
  { id_alumno: "22", nombre: "Partente Ciro ", curso: "3-H", id_equipo: "3H12", github: "https:///github.com/ciropartente" },
  { id_alumno: "23", nombre: "Perego Francisco", curso: "3-H", id_equipo: "3H12", github: "https:///github.com/ciropartente" },
  { id_alumno: "24", nombre: "Maldonado Alejandro", curso: "3-H", id_equipo: "3H13", github: "https:///github.com/cpitoig" },
  { id_alumno: "25", nombre: "Martinez  Ignacio", curso: "3-H", id_equipo: "3H13", github: "https:///github.com/cpitoig" },
  { id_alumno: "26", nombre: "Bohorquez  Alicia", curso: "3-H", id_equipo: "3H14", github: "https:///github.com/cami-l5" },
  { id_alumno: "27", nombre: "Lorefice Camila", curso: "3-H", id_equipo: "3H14", github: "https:///github.com/cami-l5" },
  { id_alumno: "28", nombre: "Bertero Ulises", curso: "3-H", id_equipo: "3H15", github: "https:///github.com/gaspi1ulises2" },
  { id_alumno: "29", nombre: "Hernández Gastón", curso: "3-H", id_equipo: "3H15", github: "https:///github.com/gaspi1ulises2" },
  { id_alumno: "30", nombre: "Rapetti Martín", curso: "3-H", id_equipo: "3H16", github: "https:///github.com/evoymartin" },
  { id_alumno: "31", nombre: "Cancino Evo", curso: "3-H", id_equipo: "3H16", github: "https:///github.com/evoymartin" },
  { id_alumno: "32", nombre: "Berto Juan Ignacio", curso: "3-H", id_equipo: "3H17", github: "https:///github.com/juaniguada1111" },
  { id_alumno: "33", nombre: "Silveira  Guadalupe", curso: "3-H", id_equipo: "3H17", github: "https:///github.com/juaniguada1111" },
  { id_alumno: "34", nombre: "Perero Juan", curso: "3-H", id_equipo: "3H18", github: "https:///github.com/juan94689" },
  { id_alumno: "35", nombre: "Leaño Yerik", curso: "3-H", id_equipo: "3H18", github: "https:///github.com/juan94689" },
  { id_alumno: "36", nombre: "Fernández Benjamin", curso: "3-H", id_equipo: "3H19", github: "https://github.com/Miliscarfo?tab=repositories" },
  { id_alumno: "37", nombre: "Scarfo Milagros", curso: "3-H", id_equipo: "3H19", github: "https://github.com/Miliscarfo?tab=repositories" },
  // 3C
  { id_alumno: "38", nombre: "Mártin Sofía", curso: "3-C", id_equipo: "3C1", github: "https://github.com/sofymartin" },
  { id_alumno: "39", nombre: "Brusco Catalina", curso: "3-C", id_equipo: "3C2", github: "https://github.com/catabruscoo" },
  { id_alumno: "40", nombre: "Scarfo Macarena", curso: "3-C", id_equipo: "3C2", github: "https://github.com/macarenascarfo" },
  { id_alumno: "41", nombre: "Ares Catalina", curso: "3-C", id_equipo: "3C3", github: "https://github.com/cataaress" },
  { id_alumno: "42", nombre: "Monet Victoria", curso: "3-C", id_equipo: "3C3", github: "https://github.com/vickymonet" },
  { id_alumno: "43", nombre: "Lovece Florencia", curso: "3-C", id_equipo: "3C4", github: "https://github.com/florlovece" },
  { id_alumno: "44", nombre: "Di´Leva Valentina", curso: "3-C", id_equipo: "3C4", github: "https://github.com/valentinadileva" },
  { id_alumno: "45", nombre: "Avendaño Tomás", curso: "3-C", id_equipo: "3C5", github: "https://github.com/tomiaven" },
  { id_alumno: "46", nombre: "Munte Santiago", curso: "3-C", id_equipo: "3C5", github: "https://github.com/santimunte" },
  { id_alumno: "47", nombre: "Gamarra Matías", curso: "3-C", id_equipo: "3C6", github: "https://github.com/m4t4t14s" },
  { id_alumno: "48", nombre: "Pérez Juan Cruz", curso: "3-C", id_equipo: "3C6", github: "https://github.com/juan-cruz-perez" },
  { id_alumno: "49", nombre: "D´Agata Francisca", curso: "3-C", id_equipo: "3C7", github: "https://github.com/francisca11ch" },
  { id_alumno: "50", nombre: "Aguirre Zaira", curso: "3-C", id_equipo: "3C7", github: "https://github.com/zairaaguirre" },
  { id_alumno: "51", nombre: "Maríncola Joaquin", curso: "3-C", id_equipo: "3C8", github: "https://github.com/depompeyavengo22" },
  { id_alumno: "52", nombre: "Talachenko Nicolás", curso: "3-C", id_equipo: "3C8", github: "https://github.com/nicotala912" },
  { id_alumno: "53", nombre: "Facedo Isabella", curso: "3-C", id_equipo: "3C9", github: "https://github.com/isa-facedo" },
  { id_alumno: "54", nombre: "Piro Joaquín", curso: "3-C", id_equipo: "3C10", github: "https://github.com/joaquinpirochino" },
  { id_alumno: "55", nombre: "Silva Lautaro", curso: "3-C", id_equipo: "3C10", github: "https://github.com/lautaro12345678910" },
  { id_alumno: "56", nombre: "Solis André", curso: "3-C", id_equipo: "3C11", github: "https://github.com/andre-solis" },
  { id_alumno: "57", nombre: "Naveda Diego", curso: "3-C", id_equipo: "3C11", github: "https://github.com/diegonaveaa" },
 //3E
  { id_alumno: "58", nombre: "Contarino Martin", curso: "3-E", id_equipo: "3E1", github: "https://github.com/martinc2521" },
  { id_alumno: "59", nombre: "Diaz Luciano", curso: "3-E", id_equipo: "3E1", github: "https://github.com/luciano985" },
  { id_alumno: "60", nombre: "Szer Valentin", curso: "3-E", id_equipo: "3E1", github: "https://github.com/valenxeneize28" },
  { id_alumno: "61", nombre: "Carena Tomás", curso: "3-E", id_equipo: "3E2", github: "https://github.com/tomicar10" },
  { id_alumno: "62", nombre: "Godoy Diego", curso: "3-E", id_equipo: "3E2", github: "https://github.com/gododoy" },
  { id_alumno: "63", nombre: "Villanustre Felipe", curso: "3-E", id_equipo: "3E2", github: "https://github.com/felivilla10" },
  { id_alumno: "64", nombre: "Luini Sofía", curso: "3-E", id_equipo: "3E3", github: "https://github.com/sofialuini302010" },
  { id_alumno: "65", nombre: "Moreno Catalina", curso: "3-E", id_equipo: "3E3", github: "https://github.com/catauuu" },
  { id_alumno: "66", nombre: "De los Rios Pilar", curso: "3-E", id_equipo: "3E4", github: "https://github.com/pilar09161" },
  { id_alumno: "67", nombre: "Scattarella Trinidad", curso: "3-E", id_equipo: "3E4", github: "https://github.com/triniscatta" },
  { id_alumno: "68", nombre: "Alonso Sofia", curso: "3-E", id_equipo: "3E5", github: "https://github.com/salonsochanuar" },
  { id_alumno: "69", nombre: "Diaz Agustín", curso: "3-E", id_equipo: "3E5", github: "https://github.com/agustinypuntofinal" },
  { id_alumno: "70", nombre: "López Lara", curso: "3-E", id_equipo: "3E5", github: "https://github.com/laralopez-informatica" },
  { id_alumno: "71", nombre: "Escudero Magalí", curso: "3-E", id_equipo: "3E6", github: "https://github.com/magaescudero" },
  { id_alumno: "72", nombre: "Garbarino Candela", curso: "3-E", id_equipo: "3E6", github: "https://github.com/candelagarbarinoo" },
  { id_alumno: "73", nombre: "Gonzalez Paz", curso: "3-E", id_equipo: "3E6", github: "https://github.com/pazgonzalezherra" },
  { id_alumno: "74", nombre: "Pons María Belén", curso: "3-E", id_equipo: "3E7", github: "https://github.com/belu0425" },
  { id_alumno: "75", nombre: "Turletti Ambar", curso: "3-E", id_equipo: "3E7", github: "https://github.com/ambar890" },
  { id_alumno: "76", nombre: "Zambrano Emily", curso: "3-E", id_equipo: "3E7", github: "https://github.com/emilyzambrano256" }
];

/*const ejercicios = [
  //3H
  { id_alumno: "1", tipo: "ejercicios", urlEjercicios: "https://solbernall.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "2", tipo: "ejercicios", urlEjercicios: "https://solbernall.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "3", tipo: "ejercicios", urlEjercicios: "https://keylacarrion00.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "4", tipo: "ejercicios", urlEjercicios: "https://keylacarrion00.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "5", tipo: "ejercicios", urlEjercicios: "https://bian200171.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "6", tipo: "ejercicios", urlEjercicios: "https://bian200171.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "7", tipo: "ejercicios", urlEjercicios: "https:///github.com/ambar-mica", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "8", tipo: "ejercicios", urlEjercicios: "https:///github.com/ambar-mica", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "9", tipo: "ejercicios", urlEjercicios: "https:///github.com/lukitasymateoficda", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "10", tipo: "ejercicios", urlEjercicios: "https:///github.com/lukitasymateoficda", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "11", tipo: "ejercicios", urlEjercicios: "https://danielcastro2010.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "12", tipo: "ejercicios", urlEjercicios: "https://danielcastro2010.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "13", tipo: "ejercicios", urlEjercicios: "https://roccoext09.github.io/INFORMATICA/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "14", tipo: "ejercicios", urlEjercicios: "https://roccoext09.github.io/INFORMATICA/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "15", tipo: "ejercicios", urlEjercicios: "https://fedealanizz.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "16", tipo: "ejercicios", urlEjercicios: "https://fedealanizz.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "17", tipo: "ejercicios", urlEjercicios: "https://sofigypalo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "18", tipo: "ejercicios", urlEjercicios: "https://sofigypalo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "19", tipo: "ejercicios", urlEjercicios: "https://grupo4-lys.github.io/taller/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "20", tipo: "ejercicios", urlEjercicios: "https://grupo4-lys.github.io/taller/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "21", tipo: "ejercicios", urlEjercicios: "https://renatacanonico.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "22", tipo: "ejercicios", urlEjercicios: "https://cpitoig.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "23", tipo: "ejercicios", urlEjercicios: "https://cpitoig.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "24", tipo: "ejercicios", urlEjercicios: "https://cpitoig.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "25", tipo: "ejercicios", urlEjercicios: "https://cpitoig.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "26", tipo: "ejercicios", urlEjercicios: "https://cami-l5.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "27", tipo: "ejercicios", urlEjercicios: "https://cami-l5.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "28", tipo: "ejercicios", urlEjercicios: "https://gaspi1ulises2.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "29", tipo: "ejercicios", urlEjercicios: "https://gaspi1ulises2.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "30", tipo: "ejercicios", urlEjercicios: "https://evoymartin.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "31", tipo: "ejercicios", urlEjercicios: "https://evoymartin.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "32", tipo: "ejercicios", urlEjercicios: "https://juaniguada1111.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "33", tipo: "ejercicios", urlEjercicios: "https://juaniguada1111.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "34", tipo: "ejercicios", urlEjercicios: "https://juan94689.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "35", tipo: "ejercicios", urlEjercicios: "https://juan94689.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "36", tipo: "ejercicios", urlEjercicios: "https://miliscarfo.github.io/scarfo-y-benja", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "37", tipo: "ejercicios", urlEjercicios: "https://miliscarfo.github.io/scarfo-y-benja", img: "img/ejercicios.jpg", destacado: false },
 
//3C 
  { id_alumno: "38", tipo: "ejercicios", urlEjercicios: "https://sofymartin.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "39", tipo: "ejercicios", urlEjercicios: "https://catabruscoo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "40", tipo: "ejercicios", urlEjercicios: "https://macarenascarfo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "41", tipo: "ejercicios", urlEjercicios: "https://cataaress.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "42", tipo: "ejercicios", urlEjercicios: "https://vickymonet.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "43", tipo: "ejercicios", urlEjercicios: "https://florlovece.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "44", tipo: "ejercicios", urlEjercicios: "https://valentinadileva.github.io/Taller/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "45", tipo: "ejercicios", urlEjercicios: "https://tomiaven.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "46", tipo: "ejercicios", urlEjercicios: "https://santimunte.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "47", tipo: "ejercicios", urlEjercicios: "https://m4t4t14s.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "48", tipo: "ejercicios", urlEjercicios: "https://juan-cruz-perez.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "49", tipo: "ejercicios", urlEjercicios: "https://francisca11ch.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "50", tipo: "ejercicios", urlEjercicios: "https://zairaaguirre.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "51", tipo: "ejercicios", urlEjercicios: "https://depompeyavengo22.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "52", tipo: "ejercicios", urlEjercicios: "https://nicotala912.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "53", tipo: "ejercicios", urlEjercicios: "https://isa-facedo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "54", tipo: "ejercicios", urlEjercicios: "https://joaquinpirochino.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "55", tipo: "ejercicios", urlEjercicios: "https://lautaro12345678910.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "56", tipo: "ejercicios", urlEjercicios: "https://andre-solis.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "57", tipo: "ejercicios", urlEjercicios: "https://diegonaveaa.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },

  //3E
   { id_alumno: "58", tipo: "ejercicios", urlEjercicios: "https://martinc2521.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "59", tipo: "ejercicios", urlEjercicios: "https://luciano985.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "60", tipo: "ejercicios", urlEjercicios: "https://valenxeneize28.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "61", tipo: "ejercicios", urlEjercicios: "https://tomicar10.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "62", tipo: "ejercicios", urlEjercicios: "https://gododoy.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "63", tipo: "ejercicios", urlEjercicios: "https://felivilla10.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "64", tipo: "ejercicios", urlEjercicios: "https://sofialuini302010.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "65", tipo: "ejercicios", urlEjercicios: "https://catauuu.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "66", tipo: "ejercicios", urlEjercicios: "https://pilar09161.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "67", tipo: "ejercicios", urlEjercicios: "https://triniscatta.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "68", tipo: "ejercicios", urlEjercicios: "https://salonsochanuar.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "69", tipo: "ejercicios", urlEjercicios: "https://agustinypuntofinal.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "70", tipo: "ejercicios", urlEjercicios: "https://laralopez-informatica.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "71", tipo: "ejercicios", urlEjercicios: "https://magaescudero.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "72", tipo: "ejercicios", urlEjercicios: "https://candelagarbarinoo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "73", tipo: "ejercicios", urlEjercicios: "https://pazgonzalezherra.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "74", tipo: "ejercicios", urlEjercicios: "https://belu0425.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "75", tipo: "ejercicios", urlEjercicios: "https://ambar890.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "76", tipo: "ejercicios", urlEjercicios: "https://emilyzambrano256.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false }

];*/

const ejercicios = [
  //3H
  { id_equipo: "3H1", tipo: "ejercicios", urlEjercicios: "https://solbernall.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H2", tipo: "ejercicios", urlEjercicios: "https://keylacarrion00.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H3", tipo: "ejercicios", urlEjercicios: "https://bian200171.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H4", tipo: "ejercicios", urlEjercicios: "https:///github.com/ambar-mica", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H5", tipo: "ejercicios", urlEjercicios: "https:///github.com/lukitasymateoficda", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H6", tipo: "ejercicios", urlEjercicios: "https://danielcastro2010.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H7", tipo: "ejercicios", urlEjercicios: "https://roccoext09.github.io/INFORMATICA/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H8", tipo: "ejercicios", urlEjercicios: "https://fedealanizz.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H9", tipo: "ejercicios", urlEjercicios: "https://sofigypalo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false},
  { id_equipo: "3H10", tipo: "ejercicios", urlEjercicios: "https://grupo4-lys.github.io/taller/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H11", tipo: "ejercicios", urlEjercicios: "https://renatacanonico.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H12", tipo: "ejercicios", urlEjercicios: "https://ciropartente.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H13", tipo: "ejercicios", urlEjercicios: "https://cpitoig.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H14", tipo: "ejercicios", urlEjercicios: "https://cami-l5.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H15", tipo: "ejercicios", urlEjercicios: "https://gaspi1ulises2.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H16", tipo: "ejercicios", urlEjercicios: "https://evoymartin.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H17", tipo: "ejercicios", urlEjercicios: "https://juaniguada1111.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H18", tipo: "ejercicios", urlEjercicios: "https://juan94689.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_equipo: "3H19", tipo: "ejercicios", urlEjercicios: "https://miliscarfo.github.io/scarfo-y-benja", img: "img/ejercicios.jpg", destacado: false },
//3C
  { id_alumno: "38", tipo: "ejercicios", urlEjercicios: "https://sofymartin.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "39", tipo: "ejercicios", urlEjercicios: "https://catabruscoo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "40", tipo: "ejercicios", urlEjercicios: "https://macarenascarfo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "41", tipo: "ejercicios", urlEjercicios: "https://cataaress.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "42", tipo: "ejercicios", urlEjercicios: "https://vickymonet.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "43", tipo: "ejercicios", urlEjercicios: "https://florlovece.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "44", tipo: "ejercicios", urlEjercicios: "https://valentinadileva.github.io/Taller/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "45", tipo: "ejercicios", urlEjercicios: "https://tomiaven.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "46", tipo: "ejercicios", urlEjercicios: "https://santimunte.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "47", tipo: "ejercicios", urlEjercicios: "https://m4t4t14s.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "48", tipo: "ejercicios", urlEjercicios: "https://juan-cruz-perez.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "49", tipo: "ejercicios", urlEjercicios: "https://francisca11ch.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "50", tipo: "ejercicios", urlEjercicios: "https://zairaaguirre.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "51", tipo: "ejercicios", urlEjercicios: "https://depompeyavengo22.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "52", tipo: "ejercicios", urlEjercicios: "https://nicotala912.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "53", tipo: "ejercicios", urlEjercicios: "https://isa-facedo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "54", tipo: "ejercicios", urlEjercicios: "https://joaquinpirochino.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "55", tipo: "ejercicios", urlEjercicios: "https://lautaro12345678910.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "56", tipo: "ejercicios", urlEjercicios: "https://andre-solis.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "57", tipo: "ejercicios", urlEjercicios: "https://diegonaveaa.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },

  //3E
   { id_alumno: "58", tipo: "ejercicios", urlEjercicios: "https://martinc2521.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "59", tipo: "ejercicios", urlEjercicios: "https://luciano985.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "60", tipo: "ejercicios", urlEjercicios: "https://valenxeneize28.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "61", tipo: "ejercicios", urlEjercicios: "https://tomicar10.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "62", tipo: "ejercicios", urlEjercicios: "https://gododoy.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "63", tipo: "ejercicios", urlEjercicios: "https://felivilla10.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "64", tipo: "ejercicios", urlEjercicios: "https://sofialuini302010.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "65", tipo: "ejercicios", urlEjercicios: "https://catauuu.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "66", tipo: "ejercicios", urlEjercicios: "https://pilar09161.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "67", tipo: "ejercicios", urlEjercicios: "https://triniscatta.github.io/Informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "68", tipo: "ejercicios", urlEjercicios: "https://salonsochanuar.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "69", tipo: "ejercicios", urlEjercicios: "https://agustinypuntofinal.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "70", tipo: "ejercicios", urlEjercicios: "https://laralopez-informatica.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "71", tipo: "ejercicios", urlEjercicios: "https://magaescudero.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "72", tipo: "ejercicios", urlEjercicios: "https://candelagarbarinoo.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "73", tipo: "ejercicios", urlEjercicios: "https://pazgonzalezherra.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "74", tipo: "ejercicios", urlEjercicios: "https://belu0425.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "75", tipo: "ejercicios", urlEjercicios: "https://ambar890.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false },
  { id_alumno: "76", tipo: "ejercicios", urlEjercicios: "https://emilyzambrano256.github.io/informatica/", img: "img/ejercicios.jpg", destacado: false }

];

const proyectos = [
  //3H
  { id_equipo: "3H1", personaje: "San Pompilio María Pirrotti", tipo: "proyecto", urlProyecto: "https://solbernall.github.io/Proyecto/", img: "img/SanPompilioMariaPirrotti.jpg", destacado: false },
  { id_equipo: "3H2", personaje: "Beato Domingo De Jesús", tipo: "proyecto", urlProyecto: "https://keylacarrion00.github.io/proyecto/", img: "img/BeatoDomingoDeJesus.jpg", destacado: false },
  { id_equipo: "3H3", personaje: "San Lorenzo", tipo: "proyecto", urlProyecto: "https://bian200171.github.io/proyecto/", img: "img/SanLorenzo.jpg", destacado: false },
  { id_equipo: "3H4", personaje: "Beato Manuel Segura López", tipo: "proyecto", urlProyecto: "https://ambar-mica.github.io/Proyecto/", img: "img/BeatoManuelSeguraLopez.jpg", destacado: false },
  { id_equipo: "3H5", personaje: "Beato Alfredo Parte", tipo: "proyecto", urlProyecto: "https://lukitasymateoficda.github.io/Proyecto-1/", img: "img/BeatoAlfredoParte.jpg", destacado: false },
  { id_equipo: "3H6", personaje: "Beato Pedro Casani", tipo: "proyecto", urlProyecto: "https://danielcastro2010.github.io/Proyecto/", img: "img/BeatoPedroCasani.jpg", destacado: false },
  { id_equipo: "3H7", personaje: "Beato David De Vergara", tipo: "proyecto", urlProyecto: "https://roccoext09.github.io/PROYECTO/", img: "img/BeatoDavidDeVergara.jpg", destacado: false },
  { id_equipo: "3H8", personaje: "Beato Faustino Oteiza Segura", tipo: "proyecto", urlProyecto: "https://fedealanizz.github.io/proyecto/", img: "img/BeatoFaustinoOteizaSegura.jpg", destacado: false },
  { id_equipo: "3H9", personaje: "Beato Dionisio Pamplona", tipo: "proyecto", urlProyecto: "https://sofigypalo.github.io/proyecto/", img: "img/BeatoDionisioPamplona.jpg", destacado: false },
  { id_equipo: "3H10", personaje: "", tipo: "proyecto", urlProyecto: "", img: "",  destacado: false },
  {  id_equipo: "3H11", personaje: "San Faustino Miguez", tipo: "proyecto", urlProyecto: "https://renatacanonico.github.io/proyecto-1/", img: "img/SanFaustinoMiguez.jpg", destacado: false },
  { id_equipo: "3H12", personaje: "Mártir José Sánchez del Río", tipo: "proyecto", urlProyecto: "https://maryzambrano.github.io/calasanz/3ro/ProyectoPartente/index.html", img: "img/MartirJoseSanchezdelRio.jpg", destacado: false },
  { id_equipo: "3H13", personaje: "Beato Ignacio Caselles García", tipo: "proyecto", urlProyecto: "https://cpitoig.github.io/Proyecto1/", img: "img/SinImagen.jpg", destacado: false },
  { id_equipo: "3H14", personaje: "Beato Glicerio Landriani", tipo: "proyecto", urlProyecto: "https://cami-l5.github.io/Proyecto/", img: "img/BeatoGlicerioLandriani.jpg", destacado: false },
  { id_equipo: "3H15", personaje: "Beato José Ferrer Esteve", tipo: "proyecto", urlProyecto: "https://gaspi1ulises2.github.io/gaspi21proyecto/", img: "img/BeatoJoseFerrerEsteve.jpg", destacado: false },
  { id_equipo: "3H16", personaje: "Beato Florentino Asensio Barroso", tipo: "proyecto", urlProyecto: "https://evoymartin.github.io/proyecto/", img: "img/BeatoFlorentinoAsensioBarroso.jpg", destacado: false },
  { id_equipo: "3H17", personaje: "Beato Florentin Felipe Naya", tipo: "proyecto", urlProyecto: "https://juaniguada1111.github.io/proyecto-/", img: "img/BeatoFlorentinFelipeNaya.jpg", destacado: false },
  { id_equipo: "3H18", personaje: "Beato Ignacio Casanovas Perramón", tipo: "proyecto", urlProyecto: "https://juan94689.github.io/Proyecto/", img: "img/BeatoIgnacioCasanovasPerramon.jpg", destacado: false },
  { id_equipo: "3H19", personaje: "Beato Pedro Casani", tipo: "proyecto", urlProyecto: "https://miliscarfo.github.io/Proyecto/", img: "img/BeatoPedroCasani.jpg", destacado: false },
  //3C
  { id_equipo: "3C1", personaje: "San Faustino Miguez", tipo: "proyecto", urlProyecto: "https://sofymartin.github.io/proyecto/", img: "img/SanFaustinoMiguez.jpg", destacado: false },
  { id_equipo: "3C2", personaje: "Beato Pedro Casani", tipo: "proyecto", urlProyecto: "https://catabruscoo.github.io/PROYECTO/", img: "img/BeatoPedroCasani.jpg", destacado: false },
  { id_equipo: "3C3", personaje: "Beato Faustino Oteiza Segura", tipo: "proyecto", urlProyecto: "https://vickymonet.github.io/Proyecto/", img: "img/BeatoFaustinoOteizaSegura.jpg", destacado: false },
  { id_equipo: "3C4", personaje: "Beato Glicerio Landriani", tipo: "proyecto", urlProyecto: "https://florlovece.github.io/Proyecto1/", img: "img/BeatoGlicerioLandriani.jpg", destacado: false },
  { id_equipo: "3C5", personaje: "Beato Dionisio Pamplona", tipo: "proyecto", urlProyecto: "https://tomiaven.github.io/proyecto-1/", img: "img/BeatoDionisioPamplona.jpg", destacado: false },
  { id_equipo: "3C6", personaje: "Beato Florentín Felipe Naya", tipo: "proyecto", urlProyecto: "https://m4t4t14s.github.io/proyecto.js/", img: "img/BeatoFlorentinFelipeNaya.jpg", destacado: false },
  { id_equipo: "3C7", personaje: "Beato Alfredo Parte", tipo: "proyecto", urlProyecto: "https://francisca11ch.github.io/Proyecto-1/", img: "img/BeatoAlfredoParte.jpg", destacado: false },
  { id_equipo: "3C8", personaje: "San Pompilio María Pirrotti", tipo: "proyecto", urlProyecto: "https://depompeyavengo22.github.io/Proyecto/", img: "img/SanPompilioMariaPirrotti.jpg", destacado: false },
  { id_equipo: "3C9", personaje: "Beato Faustino Oteiza Segura", tipo: "proyecto", urlProyecto: "https://maryzambrano.github.io/calasanz/3ro/ProyectoFacedo/index.html", img: "img/BeatoFaustinoOteizaSegura.jpg", destacado: false },
  { id_equipo: "3C10", personaje: "Beato Joaquín Erviti Lazcano", tipo: "proyecto", urlProyecto: "https://joaquinpirochino.github.io/Proyecto/", img: "img/BeatoJoaquinErvitiLazcano.jpeg", destacado: false },
  { id_equipo: "3C11", personaje: "Beato Manuel Segura López", tipo: "proyecto", urlProyecto: "https://maryzambrano.github.io/calasanz/3ro/ProyectoSolis/manuel.html", img: "img/BeatoManuelSeguraLopez.jpg", destacado: false },
  //3E
  { id_equipo: "3E1", personaje: "San Pompilio María Pirrotti", tipo: "proyecto", urlProyecto: "https://martinc2521.github.io/Proyecto/", img: "img/SanPompilioMariaPirrotti.jpg", destacado: false },
  { id_equipo: "3E2", personaje: "Santo Tomás de Aquino", tipo: "proyecto", urlProyecto: "https://gododoy.github.io/Proyecto-1/", img: "img/SantoTomasdeAquino.jpg", destacado: false},
  { id_equipo: "3E3", personaje: "Beato Alfredo Parte", tipo: "proyecto", urlProyecto: "https://sofialuini302010.github.io/Proyecto/", img: "img/BeatoAlfredoParte.jpg", destacado: false },
  { id_equipo: "3E4", personaje: "Beato Dionisio Pamplona", tipo: "proyecto", urlProyecto: "https://triniscatta.github.io/Proyecto/", img: "img/BeatoDionisioPamplona.jpg", destacado: false },
  { id_equipo: "3E5", personaje: "San Faustino Miguez", tipo: "proyecto", urlProyecto: "https://agustinypuntofinal.github.io/Proyecto/", img: "img/SanFaustinoMiguez.jpg", destacado: false },
  { id_equipo: "3E6", personaje: "Beato Pedro Casani", tipo: "proyecto", urlProyecto: "https://candelagarbarinoo.github.io/Proyecto/", img: "img/BeatoPedroCasani.jpg", destacado: false },
  { id_equipo: "3E7", personaje: "Beato Manuel Segura López", tipo: "proyecto", urlProyecto: "https://belu0425.github.io/Proyecto/", img: "img/BeatoManuelSeguraLopez.jpg", destacado: false },
  
];


